server:
  port: 8080
zuul:
  routes:
    auth:
      path: /login/**
      url: http://127.0.0.1:8081/
    service:
      path: /service/**
      url: http://127.0.0.1:8082/
  jwt:
    url: /login
    header: Authorization
    prefix: Bearer
    expiration: 7200000
    secret: othersnotknownit